### PR TITLE
Added more gauges and dual needle capability

### PR DESCRIPTION
**Pull request by Papafelice**
This is my first try to use kivy for an antenna control unit, the extra gauges are the result of playing around with inkscape.
The whole code should be converted to kivy language, but I did succeed so far.

### CODE REVIEW

**Comment by KeyWeeUsr** [comment]
Well, this is a big PR even if you substract the +lines from the new SVGs. The best thing would be to rebase first, then split it into multiple smaller PRs.

Also there are probably issues with encoding on Python 2:

image

and a crash with Python 3:

```
 Traceback (most recent call last):
   File "__init__.py", line 453, in <module>
     GaugeApp().run()
   File "C:\...\py35\lib\site-packages\kivy\app.py", line 802, in run
     root = self.build()
   File "__init__.py", line 391, in build
     needle_1_color=[1, 0, 0, 1])
   File "__init__.py", line 194, in __init__
     super(Gauge, self).__init__(**kwargs)
   File "C:\...\py35\lib\site-packages\kivy\uix\widget.py", line 337, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 254, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:5332)
 TypeError: object.__init__() takes no parameters
```

I'll close this one, but feel free to make new PRs with smaller changes and with fixed stuff mentioned above.

**Comment by Papafelice** [comment]
OK, I'll see what I can do. However, the new image formats require heavy changes in the class itself, so it's either all or nothing, I'm afraid.
There's no encoding issue, the Angström/s² symbol is correct. It was my test for the encoding.

**Comment by KeyWeeUsr** [comment]
I thought it was Ängström (with ä)... nevermind then. Also, about the images, are you the original author or are those just downloaded from somewhere?

**Comment by Papafelice** [comment]
I was inspired by real gauges that I have in my household and used the original image as the basis. All the other images were created by me using inkscape.

**Pull request closed without merging**
